title: "MATRIXLED | Teensy 4.0 & APA102 Ambilight"
description: "Ultra-low latency Ambilight controller using Teensy 4.0, ESP32 and APA102 / SK9822 LEDs. Includes WebUI."
theme: jekyll-theme-hacker
show_downloads: true
favicon: /assets/favicon.ico
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag